language: c
os:
  - freebsd
group: dev
addons:
  pkg:
    - racket
notifications:
  email: false
install:
  - raco pkg install --auto --name fdm
script:
  - raco test -x -p fdm
after_success:
  - raco setup --check-pkg-deps --pkgs fdm
  - raco pkg install --auto cover cover-coveralls
  - raco cover -b -f coveralls -d $TRAVIS_BUILD_DIR/coverage .
