language: c
env:
  global:
    - RACKET_DIR=~/racket
    - RACKET_VERSION=7.4
before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ~/travis-racket
  - cat ~/travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
install:
  - raco pkg install --auto --name fdm
script:
  - raco test -x -p fdm
after_success:
  - raco setup --check-pkg-deps --pkgs fdm
  - raco pkg install --auto cover cover-coveralls
  - raco cover -b -f coveralls -d $TRAVIS_BUILD_DIR/coverage .
